export const trendCategories = ['All', 'Tech', 'Business', 'Design', 'Data'];

const defaultCategoryTags = {
  Tech: 'it-jobs',
  Business: null,
  Design: 'creative-design-jobs',
  Data: 'it-jobs',
};

const roleTitlesByCategory = {
  Tech: [
    'Software Engineer',
    'Full Stack Engineer',
    'Frontend Engineer',
    'Backend Engineer',
    'DevOps Engineer',
    'Platform Engineer',
    'Site Reliability Engineer',
    'Cloud Engineer',
    'Cloud Security Engineer',
    'Security Engineer',
    'Cybersecurity Analyst',
    'QA Engineer',
    'Test Automation Engineer',
    'Mobile Engineer',
    'iOS Developer',
    'Android Developer',
    'Solutions Engineer',
    'Systems Engineer',
    'Network Engineer',
    'Embedded Software Engineer',
    'AI Engineer',
    'Machine Learning Engineer',
    'ML Platform Engineer',
    'API Engineer',
    'Staff Software Engineer',
    'Engineering Manager',
    'Technical Program Manager',
    'Release Engineer',
    'Infrastructure Engineer',
    'Application Engineer',
    'Game Developer',
    'AR VR Engineer',
    'Robotics Engineer',
    'Prompt Engineer',
    'IT Support Engineer',
    'IT Administrator',
    'Database Administrator',
    'Salesforce Developer',
    'SAP Developer',
    'Blockchain Developer',
    'Firmware Engineer',
    'Web Developer',
    'Rust Engineer',
    'Python Developer',
    'Java Developer',
    'Dot Net Developer',
    'PHP Developer',
    'Go Engineer',
    'Solutions Architect',
    'Cloud Architect',
    'Infrastructure Architect',
    'Application Security Engineer',
  ].slice(0, 50),
  Business: [
    'Product Manager',
    'Senior Product Manager',
    'Associate Product Manager',
    'Technical Product Manager',
    'Program Manager',
    'Project Manager',
    'Project Coordinator',
    'Operations Manager',
    'Business Operations Analyst',
    'Strategy Analyst',
    'Strategy Manager',
    'Management Consultant',
    'Business Analyst',
    'Customer Success Manager',
    'Customer Success Associate',
    'Account Executive',
    'Account Manager',
    'Sales Manager',
    'Sales Development Representative',
    'Partnerships Manager',
    'Business Development Manager',
    'Marketing Manager',
    'Content Strategist',
    'Content Marketing Manager',
    'Growth Manager',
    'Demand Generation Manager',
    'SEO Specialist',
    'Lifecycle Marketing Manager',
    'Brand Manager',
    'Communications Manager',
    'Public Relations Manager',
    'HR Generalist',
    'Recruiter',
    'Talent Acquisition Specialist',
    'People Operations Manager',
    'Chief of Staff',
    'Supply Chain Manager',
    'Procurement Analyst',
    'Vendor Manager',
    'Event Manager',
    'Community Manager',
    'Real Estate Analyst',
    'Operations Coordinator',
    'Office Manager',
    'Financial Planning Analyst',
    'Revenue Operations Analyst',
    'GTM Operations Manager',
    'Sustainability Consultant',
    'Healthcare Strategist',
    'Implementation Manager',
    'Business Systems Manager',
    'Customer Experience Manager',
  ].slice(0, 50),
  Design: [
    'Product Designer',
    'UX Designer',
    'UI Designer',
    'UX Researcher',
    'Service Designer',
    'Graphic Designer',
    'Visual Designer',
    'Brand Designer',
    'Motion Designer',
    'Interaction Designer',
    'Design Systems Designer',
    'Design Technologist',
    'Creative Director',
    'Art Director',
    'Content Designer',
    'Web Designer',
    'Experience Designer',
    'User Interface Designer',
    'Information Architect',
    'Industrial Designer',
    'Packaging Designer',
    'Illustration Designer',
    '3D Designer',
    'Game Designer',
    'Level Designer',
    'Presentation Designer',
    'Marketing Designer',
    'Multimedia Designer',
    'Accessibility Designer',
    'UX Writer',
    'Creative Strategist',
    'Video Editor',
    'Animator',
    'Storyboard Artist',
    'Exhibition Designer',
    'Interior Designer',
    'Retail Designer',
    'Fashion Designer',
    'Textile Designer',
    'Architectural Designer',
    'CAD Designer',
    'Landscape Designer',
    'Design Producer',
    'Visual Merchandiser',
    'Photo Editor',
    'Creative Project Manager',
    'Design Operations Manager',
    'Email Designer',
    'Research Operations Specialist',
    'Creative Producer',
    'Digital Designer',
    'Spatial Designer',
  ].slice(0, 50),
  Data: [
    'Data Analyst',
    'Senior Data Analyst',
    'Business Intelligence Analyst',
    'BI Developer',
    'Analytics Engineer',
    'Data Scientist',
    'Applied Scientist',
    'Machine Learning Scientist',
    'Research Scientist',
    'Quantitative Analyst',
    'Financial Analyst',
    'Product Analyst',
    'Marketing Analyst',
    'Operations Analyst',
    'Risk Analyst',
    'Fraud Analyst',
    'Reporting Analyst',
    'Insights Analyst',
    'Data Visualization Specialist',
    'Tableau Developer',
    'Power BI Analyst',
    'Statistician',
    'Econometrician',
    'Geospatial Analyst',
    'GIS Analyst',
    'Supply Chain Analyst',
    'Revenue Analyst',
    'Customer Insights Analyst',
    'Growth Analyst',
    'Experimentation Analyst',
    'Decision Scientist',
    'Data Governance Analyst',
    'Data Quality Analyst',
    'Database Analyst',
    'Pricing Analyst',
    'Forecasting Analyst',
    'NLP Scientist',
    'Computer Vision Scientist',
    'AI Researcher',
    'Business Systems Analyst',
    'Healthcare Data Analyst',
    'ESG Data Analyst',
    'People Analytics Analyst',
    'Sales Operations Analyst',
    'Research Analyst',
    'Market Research Analyst',
    'Actuarial Analyst',
    'Data Architect',
    'MLOps Engineer',
    'Data Operations Analyst',
    'Revenue Intelligence Analyst',
    'Analytics Consultant',
  ].slice(0, 50),
};

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildFamily(category, title) {
  const normalizedQuery = title.toLowerCase();

  return {
    slug: `${category.toLowerCase()}-${slugify(title)}`,
    title,
    category,
    what: normalizedQuery,
    categoryTag: defaultCategoryTags[category],
    linkedinQuery: normalizedQuery,
  };
}

export const designationFamiliesByCategory = Object.fromEntries(
  Object.entries(roleTitlesByCategory).map(([category, titles]) => [
    category,
    titles.map((title) => buildFamily(category, title)),
  ]),
);

export const designationFamilies = Object.values(designationFamiliesByCategory).flat();

export const spotlightFamiliesByCategory = Object.fromEntries(
  Object.entries(designationFamiliesByCategory).map(([category, families]) => [category, families.slice(0, 12)]),
);
